-- SEED PREÇOS (Stage 2A) — Subway Saci
-- Preços balcão (out/2025) + iFood (2024, desatualizado). Casa por NOME do produto.
-- Idempotente (on conflict). Execute após 02_seed_real.sql.
begin;

insert into produto_precos (produto_id, canal, tabela, preco, desatualizado)
select p.id, v.canal::canal, v.tabela, v.preco, v.desatualizado
from (values
  ('Vegetariano 15cm','balcao','A',16,false),
  ('Presunto 15cm','balcao','A',20,false),
  ('Frango Steak 15cm','balcao','A',21,false),
  ('Frango Empanado 15cm','balcao','A',21,false),
  ('Churrasco 15cm','balcao','A',22,false),
  ('Frango Defumado 15cm','balcao','A',23,false),
  ('Steack Cheddar 15cm','balcao','A',23,false),
  ('Teriack 15cm','balcao','A',24,false),
  ('BMT 15cm','balcao','A',24,false),
  ('Supreme 15cm','balcao','A',27,false),
  ('Carne Seca 15cm','balcao','A',24,false),
  ('Vegetariano 30cm','balcao','A',32,false),
  ('Presunto 30cm','balcao','A',40,false),
  ('Frango Steak 30cm','balcao','A',41,false),
  ('Frango Empanado 30cm','balcao','A',41,false),
  ('Churrasco 30cm','balcao','A',42,false),
  ('Frango Defumado 30cm','balcao','A',43,false),
  ('Steack Cheddar 30cm','balcao','A',43,false),
  ('Teriack 30cm','balcao','A',44,false),
  ('BMT 30cm','balcao','A',44,false),
  ('Supreme 30cm','balcao','A',47,false),
  ('Carne Seca 30cm','balcao','A',44,false),
  ('Salada Vegetariano','balcao','A',21,false),
  ('Salada Presunto','balcao','A',25,false),
  ('Salada Frango Steak','balcao','A',26,false),
  ('Salada Frango Empanado','balcao','A',26,false),
  ('Salada Churrasco','balcao','A',27,false),
  ('Salada Frango Defumado','balcao','A',28,false),
  ('Salada Steack Cheddar','balcao','A',28,false),
  ('Salada Teriack','balcao','A',29,false),
  ('Salada BMT','balcao','A',29,false),
  ('Salada Supreme','balcao','A',32,false),
  ('Vegetariano 15cm','balcao','B',16.5,false),
  ('Presunto 15cm','balcao','B',20.5,false),
  ('Frango Steak 15cm','balcao','B',21.5,false),
  ('Frango Empanado 15cm','balcao','B',21.5,false),
  ('Churrasco 15cm','balcao','B',22.5,false),
  ('Frango Defumado 15cm','balcao','B',23.5,false),
  ('Steack Cheddar 15cm','balcao','B',23.5,false),
  ('Teriack 15cm','balcao','B',24.5,false),
  ('BMT 15cm','balcao','B',24.5,false),
  ('Supreme 15cm','balcao','B',27.5,false),
  ('Carne Seca 15cm','balcao','B',24.5,false),
  ('Vegetariano 30cm','balcao','B',33,false),
  ('Presunto 30cm','balcao','B',40.5,false),
  ('Frango Steak 30cm','balcao','B',41.5,false),
  ('Frango Empanado 30cm','balcao','B',41.5,false),
  ('Churrasco 30cm','balcao','B',42.5,false),
  ('Frango Defumado 30cm','balcao','B',43.5,false),
  ('Steack Cheddar 30cm','balcao','B',43.5,false),
  ('Teriack 30cm','balcao','B',44.5,false),
  ('BMT 30cm','balcao','B',44.5,false),
  ('Supreme 30cm','balcao','B',47.5,false),
  ('Carne Seca 30cm','balcao','B',44.5,false),
  ('Salada Vegetariano','balcao','B',21.5,false),
  ('Salada Presunto','balcao','B',25.5,false),
  ('Salada Frango Steak','balcao','B',26.5,false),
  ('Salada Frango Empanado','balcao','B',26.5,false),
  ('Salada Churrasco','balcao','B',27.5,false),
  ('Salada Frango Defumado','balcao','B',28.5,false),
  ('Salada Steack Cheddar','balcao','B',28.5,false),
  ('Salada Teriack','balcao','B',29.5,false),
  ('Salada BMT','balcao','B',29.5,false),
  ('Salada Supreme','balcao','B',32.5,false),
  ('Vegetariano 15cm','balcao','C',17,false),
  ('Presunto 15cm','balcao','C',21,false),
  ('Frango Steak 15cm','balcao','C',22,false),
  ('Frango Empanado 15cm','balcao','C',22,false),
  ('Churrasco 15cm','balcao','C',23,false),
  ('Frango Defumado 15cm','balcao','C',24,false),
  ('Steack Cheddar 15cm','balcao','C',24,false),
  ('Teriack 15cm','balcao','C',25,false),
  ('BMT 15cm','balcao','C',25,false),
  ('Supreme 15cm','balcao','C',28,false),
  ('Carne Seca 15cm','balcao','C',25,false),
  ('Vegetariano 30cm','balcao','C',34,false),
  ('Presunto 30cm','balcao','C',41,false),
  ('Frango Steak 30cm','balcao','C',42,false),
  ('Frango Empanado 30cm','balcao','C',42,false),
  ('Churrasco 30cm','balcao','C',43,false),
  ('Frango Defumado 30cm','balcao','C',44,false),
  ('Steack Cheddar 30cm','balcao','C',44,false),
  ('Teriack 30cm','balcao','C',45,false),
  ('BMT 30cm','balcao','C',45,false),
  ('Supreme 30cm','balcao','C',48,false),
  ('Carne Seca 30cm','balcao','C',45,false),
  ('Salada Vegetariano','balcao','C',22.5,false),
  ('Salada Presunto','balcao','C',26.5,false),
  ('Salada Frango Steak','balcao','C',27.5,false),
  ('Salada Frango Empanado','balcao','C',27.5,false),
  ('Salada Churrasco','balcao','C',28.5,false),
  ('Salada Frango Defumado','balcao','C',29.5,false),
  ('Salada Steack Cheddar','balcao','C',29.5,false),
  ('Salada Teriack','balcao','C',30.5,false),
  ('Salada BMT','balcao','C',30.5,false),
  ('Salada Supreme','balcao','C',33.5,false),
  ('Vegetariano 15cm','balcao','D',17.5,false),
  ('Presunto 15cm','balcao','D',21.5,false),
  ('Frango Steak 15cm','balcao','D',22.5,false),
  ('Frango Empanado 15cm','balcao','D',22.5,false),
  ('Churrasco 15cm','balcao','D',23.5,false),
  ('Frango Defumado 15cm','balcao','D',24.5,false),
  ('Steack Cheddar 15cm','balcao','D',24.5,false),
  ('Teriack 15cm','balcao','D',25.5,false),
  ('BMT 15cm','balcao','D',25.5,false),
  ('Supreme 15cm','balcao','D',28.5,false),
  ('Carne Seca 15cm','balcao','D',25.5,false),
  ('Vegetariano 30cm','balcao','D',35,false),
  ('Presunto 30cm','balcao','D',41.5,false),
  ('Frango Steak 30cm','balcao','D',42.5,false),
  ('Frango Empanado 30cm','balcao','D',42.5,false),
  ('Churrasco 30cm','balcao','D',43.5,false),
  ('Frango Defumado 30cm','balcao','D',44.5,false),
  ('Steack Cheddar 30cm','balcao','D',44.5,false),
  ('Teriack 30cm','balcao','D',45.5,false),
  ('BMT 30cm','balcao','D',45.5,false),
  ('Supreme 30cm','balcao','D',48.5,false),
  ('Carne Seca 30cm','balcao','D',45.5,false),
  ('Salada Vegetariano','balcao','D',23,false),
  ('Salada Presunto','balcao','D',27,false),
  ('Salada Frango Steak','balcao','D',28,false),
  ('Salada Frango Empanado','balcao','D',28,false),
  ('Salada Churrasco','balcao','D',29,false),
  ('Salada Frango Defumado','balcao','D',30,false),
  ('Salada Steack Cheddar','balcao','D',30,false),
  ('Salada Teriack','balcao','D',31,false),
  ('Salada BMT','balcao','D',31,false),
  ('Salada Supreme','balcao','D',34,false),
  ('Vegetariano 15cm','balcao','E',18,false),
  ('Presunto 15cm','balcao','E',22,false),
  ('Frango Steak 15cm','balcao','E',23,false),
  ('Frango Empanado 15cm','balcao','E',23,false),
  ('Churrasco 15cm','balcao','E',24,false),
  ('Frango Defumado 15cm','balcao','E',25,false),
  ('Steack Cheddar 15cm','balcao','E',25,false),
  ('Teriack 15cm','balcao','E',26,false),
  ('BMT 15cm','balcao','E',26,false),
  ('Supreme 15cm','balcao','E',29,false),
  ('Carne Seca 15cm','balcao','E',26,false),
  ('Vegetariano 30cm','balcao','E',36,false),
  ('Presunto 30cm','balcao','E',42,false),
  ('Frango Steak 30cm','balcao','E',43,false),
  ('Frango Empanado 30cm','balcao','E',43,false),
  ('Churrasco 30cm','balcao','E',44,false),
  ('Frango Defumado 30cm','balcao','E',45,false),
  ('Steack Cheddar 30cm','balcao','E',45,false),
  ('Teriack 30cm','balcao','E',46,false),
  ('BMT 30cm','balcao','E',46,false),
  ('Supreme 30cm','balcao','E',49,false),
  ('Carne Seca 30cm','balcao','E',46,false),
  ('Salada Vegetariano','balcao','E',24,false),
  ('Salada Presunto','balcao','E',28,false),
  ('Salada Frango Steak','balcao','E',29,false),
  ('Salada Frango Empanado','balcao','E',29,false),
  ('Salada Churrasco','balcao','E',30,false),
  ('Salada Frango Defumado','balcao','E',31,false),
  ('Salada Steack Cheddar','balcao','E',31,false),
  ('Salada Teriack','balcao','E',32,false),
  ('Salada BMT','balcao','E',32,false),
  ('Salada Supreme','balcao','E',35,false),
  ('Vegetariano 15cm','balcao','F',18.5,false),
  ('Presunto 15cm','balcao','F',22.5,false),
  ('Frango Steak 15cm','balcao','F',23.5,false),
  ('Frango Empanado 15cm','balcao','F',23.5,false),
  ('Churrasco 15cm','balcao','F',24.5,false),
  ('Frango Defumado 15cm','balcao','F',25.5,false),
  ('Steack Cheddar 15cm','balcao','F',25.5,false),
  ('Teriack 15cm','balcao','F',26.5,false),
  ('BMT 15cm','balcao','F',26.5,false),
  ('Supreme 15cm','balcao','F',29.5,false),
  ('Carne Seca 15cm','balcao','F',26.5,false),
  ('Vegetariano 30cm','balcao','F',37,false),
  ('Presunto 30cm','balcao','F',42.5,false),
  ('Frango Steak 30cm','balcao','F',43.5,false),
  ('Frango Empanado 30cm','balcao','F',43.5,false),
  ('Churrasco 30cm','balcao','F',44.5,false),
  ('Frango Defumado 30cm','balcao','F',45.5,false),
  ('Steack Cheddar 30cm','balcao','F',45.5,false),
  ('Teriack 30cm','balcao','F',46.5,false),
  ('BMT 30cm','balcao','F',46.5,false),
  ('Supreme 30cm','balcao','F',49.5,false),
  ('Carne Seca 30cm','balcao','F',46.5,false),
  ('Salada Vegetariano','balcao','F',24.5,false),
  ('Salada Presunto','balcao','F',28.5,false),
  ('Salada Frango Steak','balcao','F',29.5,false),
  ('Salada Frango Empanado','balcao','F',29.5,false),
  ('Salada Churrasco','balcao','F',30.5,false),
  ('Salada Frango Defumado','balcao','F',31.5,false),
  ('Salada Steack Cheddar','balcao','F',31.5,false),
  ('Salada Teriack','balcao','F',32.5,false),
  ('Salada BMT','balcao','F',32.5,false),
  ('Salada Supreme','balcao','F',35.5,false),
  ('Vegetariano 15cm','balcao','AERO A',24,false),
  ('Presunto 15cm','balcao','AERO A',29,false),
  ('Frango Steak 15cm','balcao','AERO A',30,false),
  ('Frango Empanado 15cm','balcao','AERO A',30,false),
  ('Churrasco 15cm','balcao','AERO A',31,false),
  ('Frango Defumado 15cm','balcao','AERO A',32,false),
  ('Steack Cheddar 15cm','balcao','AERO A',32,false),
  ('Teriack 15cm','balcao','AERO A',34,false),
  ('BMT 15cm','balcao','AERO A',34,false),
  ('Supreme 15cm','balcao','AERO A',37,false),
  ('Carne Seca 15cm','balcao','AERO A',34,false),
  ('Vegetariano 30cm','balcao','AERO A',48,false),
  ('Presunto 30cm','balcao','AERO A',51,false),
  ('Frango Steak 30cm','balcao','AERO A',52,false),
  ('Frango Empanado 30cm','balcao','AERO A',52,false),
  ('Churrasco 30cm','balcao','AERO A',53,false),
  ('Frango Defumado 30cm','balcao','AERO A',54,false),
  ('Steack Cheddar 30cm','balcao','AERO A',54,false),
  ('Teriack 30cm','balcao','AERO A',56,false),
  ('BMT 30cm','balcao','AERO A',56,false),
  ('Supreme 30cm','balcao','AERO A',59,false),
  ('Carne Seca 30cm','balcao','AERO A',56,false),
  ('Salada Vegetariano','balcao','AERO A',31,false),
  ('Salada Presunto','balcao','AERO A',36,false),
  ('Salada Frango Steak','balcao','AERO A',37,false),
  ('Salada Frango Empanado','balcao','AERO A',37,false),
  ('Salada Churrasco','balcao','AERO A',38,false),
  ('Salada Frango Defumado','balcao','AERO A',39,false),
  ('Salada Steack Cheddar','balcao','AERO A',39,false),
  ('Salada Teriack','balcao','AERO A',41,false),
  ('Salada BMT','balcao','AERO A',41,false),
  ('Salada Supreme','balcao','AERO A',44,false),
  ('Vegetariano 15cm','balcao','AERO B',27,false),
  ('Presunto 15cm','balcao','AERO B',32,false),
  ('Frango Steak 15cm','balcao','AERO B',33,false),
  ('Frango Empanado 15cm','balcao','AERO B',33,false),
  ('Churrasco 15cm','balcao','AERO B',34,false),
  ('Frango Defumado 15cm','balcao','AERO B',35,false),
  ('Steack Cheddar 15cm','balcao','AERO B',35,false),
  ('Teriack 15cm','balcao','AERO B',37,false),
  ('BMT 15cm','balcao','AERO B',37,false),
  ('Supreme 15cm','balcao','AERO B',40,false),
  ('Carne Seca 15cm','balcao','AERO B',37,false),
  ('Vegetariano 30cm','balcao','AERO B',54,false),
  ('Presunto 30cm','balcao','AERO B',55,false),
  ('Frango Steak 30cm','balcao','AERO B',56,false),
  ('Frango Empanado 30cm','balcao','AERO B',56,false),
  ('Churrasco 30cm','balcao','AERO B',57,false),
  ('Frango Defumado 30cm','balcao','AERO B',58,false),
  ('Steack Cheddar 30cm','balcao','AERO B',58,false),
  ('Teriack 30cm','balcao','AERO B',60,false),
  ('BMT 30cm','balcao','AERO B',60,false),
  ('Supreme 30cm','balcao','AERO B',63,false),
  ('Carne Seca 30cm','balcao','AERO B',60,false),
  ('Salada Vegetariano','balcao','AERO B',36,false),
  ('Salada Presunto','balcao','AERO B',41,false),
  ('Salada Frango Steak','balcao','AERO B',42,false),
  ('Salada Frango Empanado','balcao','AERO B',42,false),
  ('Salada Churrasco','balcao','AERO B',43,false),
  ('Salada Frango Defumado','balcao','AERO B',44,false),
  ('Salada Steack Cheddar','balcao','AERO B',44,false),
  ('Salada Teriack','balcao','AERO B',46,false),
  ('Salada BMT','balcao','AERO B',46,false),
  ('Salada Supreme','balcao','AERO B',49,false),
  ('Vegetariano 15cm','ifood','A',18,true),
  ('Vegetariano 30cm','ifood','A',36,true),
  ('Vegetariano 15cm','ifood','B',19,true),
  ('Vegetariano 30cm','ifood','B',37,true),
  ('Vegetariano 15cm','ifood','C',20,true),
  ('Vegetariano 30cm','ifood','C',38,true),
  ('Vegetariano 15cm','ifood','D',21,true),
  ('Vegetariano 30cm','ifood','D',39,true),
  ('Presunto 15cm','ifood','A',22,true),
  ('Presunto 30cm','ifood','A',40,true),
  ('Presunto 15cm','ifood','B',23,true),
  ('Presunto 30cm','ifood','B',41,true),
  ('Presunto 15cm','ifood','C',24,true),
  ('Presunto 30cm','ifood','C',42,true),
  ('Presunto 15cm','ifood','D',25,true),
  ('Presunto 30cm','ifood','D',43,true),
  ('Frango Steak 15cm','ifood','A',23,true),
  ('Frango Steak 30cm','ifood','A',41,true),
  ('Frango Steak 15cm','ifood','B',24,true),
  ('Frango Steak 30cm','ifood','B',42,true),
  ('Frango Steak 15cm','ifood','C',25,true),
  ('Frango Steak 30cm','ifood','C',43,true),
  ('Frango Steak 15cm','ifood','D',26,true),
  ('Frango Steak 30cm','ifood','D',44,true),
  ('Frango Empanado 15cm','ifood','A',23.5,true),
  ('Frango Empanado 30cm','ifood','A',41.5,true),
  ('Frango Empanado 15cm','ifood','B',24.5,true),
  ('Frango Empanado 30cm','ifood','B',42.5,true),
  ('Frango Empanado 15cm','ifood','C',25.5,true),
  ('Frango Empanado 30cm','ifood','C',43.5,true),
  ('Frango Empanado 15cm','ifood','D',26.5,true),
  ('Frango Empanado 30cm','ifood','D',44.5,true),
  ('Churrasco 15cm','ifood','A',24.5,true),
  ('Churrasco 30cm','ifood','A',42.5,true),
  ('Churrasco 15cm','ifood','B',25.5,true),
  ('Churrasco 30cm','ifood','B',43.5,true),
  ('Churrasco 15cm','ifood','C',26.5,true),
  ('Churrasco 30cm','ifood','C',44.5,true),
  ('Churrasco 15cm','ifood','D',27.5,true),
  ('Churrasco 30cm','ifood','D',45.5,true),
  ('Frango Defumado 15cm','ifood','A',25.5,true),
  ('Frango Defumado 30cm','ifood','A',43.5,true),
  ('Frango Defumado 15cm','ifood','B',26.5,true),
  ('Frango Defumado 30cm','ifood','B',44.5,true),
  ('Frango Defumado 15cm','ifood','C',27.5,true),
  ('Frango Defumado 30cm','ifood','C',45.5,true),
  ('Frango Defumado 15cm','ifood','D',28.5,true),
  ('Frango Defumado 30cm','ifood','D',46.5,true),
  ('Steack Cheddar 15cm','ifood','A',26.5,true),
  ('Steack Cheddar 30cm','ifood','A',44.5,true),
  ('Steack Cheddar 15cm','ifood','B',27.5,true),
  ('Steack Cheddar 30cm','ifood','B',45.5,true),
  ('Steack Cheddar 15cm','ifood','C',28.5,true),
  ('Steack Cheddar 30cm','ifood','C',46.5,true),
  ('Steack Cheddar 15cm','ifood','D',29.5,true),
  ('Steack Cheddar 30cm','ifood','D',47.5,true),
  ('Teriack 15cm','ifood','A',26.5,true),
  ('Teriack 30cm','ifood','A',44.5,true),
  ('Teriack 15cm','ifood','B',27.5,true),
  ('Teriack 30cm','ifood','B',45.5,true),
  ('Teriack 15cm','ifood','C',28.5,true),
  ('Teriack 30cm','ifood','C',46.5,true),
  ('Teriack 15cm','ifood','D',29.5,true),
  ('Teriack 30cm','ifood','D',47.5,true),
  ('BMT 15cm','ifood','A',27.5,true),
  ('BMT 30cm','ifood','A',45.5,true),
  ('BMT 15cm','ifood','B',28.5,true),
  ('BMT 30cm','ifood','B',46.5,true),
  ('BMT 15cm','ifood','C',29.5,true),
  ('BMT 30cm','ifood','C',47.5,true),
  ('BMT 15cm','ifood','D',30.5,true),
  ('BMT 30cm','ifood','D',48.5,true),
  ('Supreme 15cm','ifood','A',28.5,true),
  ('Supreme 30cm','ifood','A',46.5,true),
  ('Supreme 15cm','ifood','B',29.5,true),
  ('Supreme 30cm','ifood','B',47.5,true),
  ('Supreme 15cm','ifood','C',30.5,true),
  ('Supreme 30cm','ifood','C',48.5,true),
  ('Supreme 15cm','ifood','D',31.5,true),
  ('Supreme 30cm','ifood','D',49.5,true),
  ('Carne Seca 15cm','ifood','A',28.5,true),
  ('Carne Seca 30cm','ifood','A',46.5,true),
  ('Carne Seca 15cm','ifood','B',29.5,true),
  ('Carne Seca 30cm','ifood','B',47.5,true),
  ('Carne Seca 15cm','ifood','C',30.5,true),
  ('Carne Seca 30cm','ifood','C',48.5,true),
  ('Carne Seca 15cm','ifood','D',31.5,true),
  ('Carne Seca 30cm','ifood','D',49.5,true),
  ('Salada Vegetariano','ifood','A',24,true),
  ('Salada Vegetariano','ifood','B',25,true),
  ('Salada Vegetariano','ifood','C',26,true),
  ('Salada Vegetariano','ifood','D',27,true),
  ('Salada Presunto','ifood','A',28,true),
  ('Salada Presunto','ifood','B',29,true),
  ('Salada Presunto','ifood','C',30,true),
  ('Salada Presunto','ifood','D',31,true),
  ('Salada Frango Steak','ifood','A',29,true),
  ('Salada Frango Steak','ifood','B',30,true),
  ('Salada Frango Steak','ifood','C',31,true),
  ('Salada Frango Steak','ifood','D',32,true),
  ('Salada Frango Empanado','ifood','A',29.5,true),
  ('Salada Frango Empanado','ifood','B',30.5,true),
  ('Salada Frango Empanado','ifood','C',31.5,true),
  ('Salada Frango Empanado','ifood','D',32.5,true),
  ('Salada Churrasco','ifood','A',30.5,true),
  ('Salada Churrasco','ifood','B',31.5,true),
  ('Salada Churrasco','ifood','C',32.5,true),
  ('Salada Churrasco','ifood','D',33.5,true),
  ('Salada Frango Defumado','ifood','A',31.5,true),
  ('Salada Frango Defumado','ifood','B',32.5,true),
  ('Salada Frango Defumado','ifood','C',33.5,true),
  ('Salada Frango Defumado','ifood','D',34.5,true),
  ('Salada Steack Cheddar','ifood','A',32.5,true),
  ('Salada Steack Cheddar','ifood','B',33.5,true),
  ('Salada Steack Cheddar','ifood','C',34.5,true),
  ('Salada Steack Cheddar','ifood','D',35.5,true),
  ('Salada Teriack','ifood','A',32.5,true),
  ('Salada Teriack','ifood','B',33.5,true),
  ('Salada Teriack','ifood','C',34.5,true),
  ('Salada Teriack','ifood','D',35.5,true),
  ('Salada BMT','ifood','A',33.5,true),
  ('Salada BMT','ifood','B',34.5,true),
  ('Salada BMT','ifood','C',35.5,true),
  ('Salada BMT','ifood','D',36.5,true),
  ('Salada Supreme','ifood','A',34.5,true),
  ('Salada Supreme','ifood','B',35.5,true),
  ('Salada Supreme','ifood','C',36.5,true),
  ('Salada Supreme','ifood','D',37.5,true),
  ('Salada Carne Seca','ifood','A',34.5,true),
  ('Salada Carne Seca','ifood','B',35.5,true),
  ('Salada Carne Seca','ifood','C',36.5,true),
  ('Salada Carne Seca','ifood','D',37.5,true)
) as v(nome, canal, tabela, preco, desatualizado)
join produtos p on p.organizacao_id = '00000000-0000-0000-0000-000000000001' and p.nome = v.nome
on conflict (produto_id, canal, tabela)
  do update set preco = excluded.preco, desatualizado = excluded.desatualizado, atualizado_em = now();

commit;
