-- MIGRATION 008 — Preços iFood tabelas E, F, G, H, Z1, Z2, Z3, Z4
-- Fonte: (IFOOD) Tabela de Preços - Subway (3).xlsx, aba "Set 2024".
-- Estende os sanduíches (15/30cm) e saladas que já tinham iFood A–D.
-- Marcados desatualizado=true (preços de 2024). Idempotente. Rode no Supabase.
begin;
insert into produto_precos (produto_id, canal, tabela, preco, desatualizado)
select p.id, v.canal::canal, v.tabela, v.preco, v.desatualizado
from (values
  ('Vegetariano 15cm','ifood','E',22,true),
  ('Vegetariano 30cm','ifood','E',40,true),
  ('Vegetariano 15cm','ifood','F',22.5,true),
  ('Vegetariano 30cm','ifood','F',40.5,true),
  ('Vegetariano 15cm','ifood','G',23.5,true),
  ('Vegetariano 30cm','ifood','G',41.5,true),
  ('Vegetariano 15cm','ifood','H',24,true),
  ('Vegetariano 30cm','ifood','H',42,true),
  ('Vegetariano 15cm','ifood','Z1',25.5,true),
  ('Vegetariano 30cm','ifood','Z1',43.5,true),
  ('Vegetariano 15cm','ifood','Z2',26.5,true),
  ('Vegetariano 30cm','ifood','Z2',44.5,true),
  ('Vegetariano 15cm','ifood','Z3',27.5,true),
  ('Vegetariano 30cm','ifood','Z3',45.5,true),
  ('Vegetariano 15cm','ifood','Z4',28.5,true),
  ('Vegetariano 30cm','ifood','Z4',46.5,true),
  ('Presunto 15cm','ifood','E',26,true),
  ('Presunto 30cm','ifood','E',44,true),
  ('Presunto 15cm','ifood','F',26.5,true),
  ('Presunto 30cm','ifood','F',44.5,true),
  ('Presunto 15cm','ifood','G',27.5,true),
  ('Presunto 30cm','ifood','G',45.5,true),
  ('Presunto 15cm','ifood','H',28,true),
  ('Presunto 30cm','ifood','H',46,true),
  ('Presunto 15cm','ifood','Z1',29.5,true),
  ('Presunto 30cm','ifood','Z1',47.5,true),
  ('Presunto 15cm','ifood','Z2',30.5,true),
  ('Presunto 30cm','ifood','Z2',48.5,true),
  ('Presunto 15cm','ifood','Z3',31.5,true),
  ('Presunto 30cm','ifood','Z3',49.5,true),
  ('Presunto 15cm','ifood','Z4',32.5,true),
  ('Presunto 30cm','ifood','Z4',50.5,true),
  ('Frango Steak 15cm','ifood','E',27,true),
  ('Frango Steak 30cm','ifood','E',45,true),
  ('Frango Steak 15cm','ifood','F',27.5,true),
  ('Frango Steak 30cm','ifood','F',45.5,true),
  ('Frango Steak 15cm','ifood','G',28.5,true),
  ('Frango Steak 30cm','ifood','G',46.5,true),
  ('Frango Steak 15cm','ifood','H',29,true),
  ('Frango Steak 30cm','ifood','H',47,true),
  ('Frango Steak 15cm','ifood','Z1',30.5,true),
  ('Frango Steak 30cm','ifood','Z1',48.5,true),
  ('Frango Steak 15cm','ifood','Z2',31.5,true),
  ('Frango Steak 30cm','ifood','Z2',49.5,true),
  ('Frango Steak 15cm','ifood','Z3',32.5,true),
  ('Frango Steak 30cm','ifood','Z3',50.5,true),
  ('Frango Steak 15cm','ifood','Z4',33.5,true),
  ('Frango Steak 30cm','ifood','Z4',51.5,true),
  ('Frango Empanado 15cm','ifood','E',27.5,true),
  ('Frango Empanado 30cm','ifood','E',45.5,true),
  ('Frango Empanado 15cm','ifood','F',28,true),
  ('Frango Empanado 30cm','ifood','F',46,true),
  ('Frango Empanado 15cm','ifood','G',29,true),
  ('Frango Empanado 30cm','ifood','G',47,true),
  ('Frango Empanado 15cm','ifood','H',29.5,true),
  ('Frango Empanado 30cm','ifood','H',47.5,true),
  ('Frango Empanado 15cm','ifood','Z1',31,true),
  ('Frango Empanado 30cm','ifood','Z1',49,true),
  ('Frango Empanado 15cm','ifood','Z2',32,true),
  ('Frango Empanado 30cm','ifood','Z2',50,true),
  ('Frango Empanado 15cm','ifood','Z3',33,true),
  ('Frango Empanado 30cm','ifood','Z3',51,true),
  ('Frango Empanado 15cm','ifood','Z4',34,true),
  ('Frango Empanado 30cm','ifood','Z4',52,true),
  ('Churrasco 15cm','ifood','E',28.5,true),
  ('Churrasco 30cm','ifood','E',46.5,true),
  ('Churrasco 15cm','ifood','F',29,true),
  ('Churrasco 30cm','ifood','F',47,true),
  ('Churrasco 15cm','ifood','G',30,true),
  ('Churrasco 30cm','ifood','G',48,true),
  ('Churrasco 15cm','ifood','H',30.5,true),
  ('Churrasco 30cm','ifood','H',48.5,true),
  ('Churrasco 15cm','ifood','Z1',32,true),
  ('Churrasco 30cm','ifood','Z1',50,true),
  ('Churrasco 15cm','ifood','Z2',33,true),
  ('Churrasco 30cm','ifood','Z2',51,true),
  ('Churrasco 15cm','ifood','Z3',34,true),
  ('Churrasco 30cm','ifood','Z3',52,true),
  ('Churrasco 15cm','ifood','Z4',35,true),
  ('Churrasco 30cm','ifood','Z4',53,true),
  ('Frango Defumado 15cm','ifood','E',29.5,true),
  ('Frango Defumado 30cm','ifood','E',47.5,true),
  ('Frango Defumado 15cm','ifood','F',30,true),
  ('Frango Defumado 30cm','ifood','F',48,true),
  ('Frango Defumado 15cm','ifood','G',31,true),
  ('Frango Defumado 30cm','ifood','G',49,true),
  ('Frango Defumado 15cm','ifood','H',31.5,true),
  ('Frango Defumado 30cm','ifood','H',49.5,true),
  ('Frango Defumado 15cm','ifood','Z1',33,true),
  ('Frango Defumado 30cm','ifood','Z1',51,true),
  ('Frango Defumado 15cm','ifood','Z2',34,true),
  ('Frango Defumado 30cm','ifood','Z2',52,true),
  ('Frango Defumado 15cm','ifood','Z3',35,true),
  ('Frango Defumado 30cm','ifood','Z3',53,true),
  ('Frango Defumado 15cm','ifood','Z4',36,true),
  ('Frango Defumado 30cm','ifood','Z4',54,true),
  ('Steack Cheddar 15cm','ifood','E',30.5,true),
  ('Steack Cheddar 30cm','ifood','E',48.5,true),
  ('Steack Cheddar 15cm','ifood','F',31,true),
  ('Steack Cheddar 30cm','ifood','F',49,true),
  ('Steack Cheddar 15cm','ifood','G',32,true),
  ('Steack Cheddar 30cm','ifood','G',50,true),
  ('Steack Cheddar 15cm','ifood','H',32.5,true),
  ('Steack Cheddar 30cm','ifood','H',50.5,true),
  ('Steack Cheddar 15cm','ifood','Z1',34,true),
  ('Steack Cheddar 30cm','ifood','Z1',52,true),
  ('Steack Cheddar 15cm','ifood','Z2',35,true),
  ('Steack Cheddar 30cm','ifood','Z2',53,true),
  ('Steack Cheddar 15cm','ifood','Z3',36,true),
  ('Steack Cheddar 30cm','ifood','Z3',54,true),
  ('Steack Cheddar 15cm','ifood','Z4',37,true),
  ('Steack Cheddar 30cm','ifood','Z4',55,true),
  ('Teriack 15cm','ifood','E',30.5,true),
  ('Teriack 30cm','ifood','E',48.5,true),
  ('Teriack 15cm','ifood','F',31,true),
  ('Teriack 30cm','ifood','F',49,true),
  ('Teriack 15cm','ifood','G',32,true),
  ('Teriack 30cm','ifood','G',50,true),
  ('Teriack 15cm','ifood','H',32.5,true),
  ('Teriack 30cm','ifood','H',50.5,true),
  ('Teriack 15cm','ifood','Z1',34,true),
  ('Teriack 30cm','ifood','Z1',52,true),
  ('Teriack 15cm','ifood','Z2',35,true),
  ('Teriack 30cm','ifood','Z2',53,true),
  ('Teriack 15cm','ifood','Z3',36,true),
  ('Teriack 30cm','ifood','Z3',54,true),
  ('Teriack 15cm','ifood','Z4',37,true),
  ('Teriack 30cm','ifood','Z4',55,true),
  ('BMT 15cm','ifood','E',31.5,true),
  ('BMT 30cm','ifood','E',49.5,true),
  ('BMT 15cm','ifood','F',32,true),
  ('BMT 30cm','ifood','F',50,true),
  ('BMT 15cm','ifood','G',33,true),
  ('BMT 30cm','ifood','G',51,true),
  ('BMT 15cm','ifood','H',33.5,true),
  ('BMT 30cm','ifood','H',51.5,true),
  ('BMT 15cm','ifood','Z1',35,true),
  ('BMT 30cm','ifood','Z1',53,true),
  ('BMT 15cm','ifood','Z2',36,true),
  ('BMT 30cm','ifood','Z2',54,true),
  ('BMT 15cm','ifood','Z3',37,true),
  ('BMT 30cm','ifood','Z3',55,true),
  ('BMT 15cm','ifood','Z4',38,true),
  ('BMT 30cm','ifood','Z4',56,true),
  ('Supreme 15cm','ifood','E',32.5,true),
  ('Supreme 30cm','ifood','E',50.5,true),
  ('Supreme 15cm','ifood','F',33,true),
  ('Supreme 30cm','ifood','F',51,true),
  ('Supreme 15cm','ifood','G',34,true),
  ('Supreme 30cm','ifood','G',52,true),
  ('Supreme 15cm','ifood','H',34.5,true),
  ('Supreme 30cm','ifood','H',52.5,true),
  ('Supreme 15cm','ifood','Z1',36,true),
  ('Supreme 30cm','ifood','Z1',54,true),
  ('Supreme 15cm','ifood','Z2',37,true),
  ('Supreme 30cm','ifood','Z2',55,true),
  ('Supreme 15cm','ifood','Z3',38,true),
  ('Supreme 30cm','ifood','Z3',56,true),
  ('Supreme 15cm','ifood','Z4',39,true),
  ('Supreme 30cm','ifood','Z4',57,true),
  ('Carne Seca 15cm','ifood','E',32.5,true),
  ('Carne Seca 30cm','ifood','E',50.5,true),
  ('Carne Seca 15cm','ifood','F',33,true),
  ('Carne Seca 30cm','ifood','F',51,true),
  ('Carne Seca 15cm','ifood','G',34,true),
  ('Carne Seca 30cm','ifood','G',52,true),
  ('Carne Seca 15cm','ifood','H',34.5,true),
  ('Carne Seca 30cm','ifood','H',52.5,true),
  ('Carne Seca 15cm','ifood','Z1',36,true),
  ('Carne Seca 30cm','ifood','Z1',54,true),
  ('Carne Seca 15cm','ifood','Z2',37,true),
  ('Carne Seca 30cm','ifood','Z2',55,true),
  ('Carne Seca 15cm','ifood','Z3',38,true),
  ('Carne Seca 30cm','ifood','Z3',56,true),
  ('Carne Seca 15cm','ifood','Z4',39,true),
  ('Carne Seca 30cm','ifood','Z4',57,true),
  ('Salada Vegetariano','ifood','E',28,true),
  ('Salada Vegetariano','ifood','F',28.5,true),
  ('Salada Vegetariano','ifood','G',29.5,true),
  ('Salada Vegetariano','ifood','H',30,true),
  ('Salada Vegetariano','ifood','Z1',31.5,true),
  ('Salada Vegetariano','ifood','Z2',32.5,true),
  ('Salada Vegetariano','ifood','Z3',33.5,true),
  ('Salada Vegetariano','ifood','Z4',34.5,true),
  ('Salada Presunto','ifood','E',32,true),
  ('Salada Presunto','ifood','F',32.5,true),
  ('Salada Presunto','ifood','G',33.5,true),
  ('Salada Presunto','ifood','H',34,true),
  ('Salada Presunto','ifood','Z1',35.5,true),
  ('Salada Presunto','ifood','Z2',36.5,true),
  ('Salada Presunto','ifood','Z3',37.5,true),
  ('Salada Presunto','ifood','Z4',38.5,true),
  ('Salada Frango Steak','ifood','E',33,true),
  ('Salada Frango Steak','ifood','F',33.5,true),
  ('Salada Frango Steak','ifood','G',34.5,true),
  ('Salada Frango Steak','ifood','H',35,true),
  ('Salada Frango Steak','ifood','Z1',36.5,true),
  ('Salada Frango Steak','ifood','Z2',37.5,true),
  ('Salada Frango Steak','ifood','Z3',38.5,true),
  ('Salada Frango Steak','ifood','Z4',39.5,true),
  ('Salada Frango Empanado','ifood','E',33.5,true),
  ('Salada Frango Empanado','ifood','F',34,true),
  ('Salada Frango Empanado','ifood','G',35,true),
  ('Salada Frango Empanado','ifood','H',35.5,true),
  ('Salada Frango Empanado','ifood','Z1',37,true),
  ('Salada Frango Empanado','ifood','Z2',38,true),
  ('Salada Frango Empanado','ifood','Z3',39,true),
  ('Salada Frango Empanado','ifood','Z4',40,true),
  ('Salada Churrasco','ifood','E',34.5,true),
  ('Salada Churrasco','ifood','F',35,true),
  ('Salada Churrasco','ifood','G',36,true),
  ('Salada Churrasco','ifood','H',36.5,true),
  ('Salada Churrasco','ifood','Z1',38,true),
  ('Salada Churrasco','ifood','Z2',39,true),
  ('Salada Churrasco','ifood','Z3',40,true),
  ('Salada Churrasco','ifood','Z4',41,true),
  ('Salada Frango Defumado','ifood','E',35.5,true),
  ('Salada Frango Defumado','ifood','F',36,true),
  ('Salada Frango Defumado','ifood','G',37,true),
  ('Salada Frango Defumado','ifood','H',37.5,true),
  ('Salada Frango Defumado','ifood','Z1',39,true),
  ('Salada Frango Defumado','ifood','Z2',40,true),
  ('Salada Frango Defumado','ifood','Z3',41,true),
  ('Salada Frango Defumado','ifood','Z4',42,true),
  ('Salada Steack Cheddar','ifood','E',36.5,true),
  ('Salada Steack Cheddar','ifood','F',37,true),
  ('Salada Steack Cheddar','ifood','G',38,true),
  ('Salada Steack Cheddar','ifood','H',38.5,true),
  ('Salada Steack Cheddar','ifood','Z1',40,true),
  ('Salada Steack Cheddar','ifood','Z2',41,true),
  ('Salada Steack Cheddar','ifood','Z3',42,true),
  ('Salada Steack Cheddar','ifood','Z4',43,true),
  ('Salada Teriack','ifood','E',36.5,true),
  ('Salada Teriack','ifood','F',37,true),
  ('Salada Teriack','ifood','G',38,true),
  ('Salada Teriack','ifood','H',38.5,true),
  ('Salada Teriack','ifood','Z1',40,true),
  ('Salada Teriack','ifood','Z2',41,true),
  ('Salada Teriack','ifood','Z3',42,true),
  ('Salada Teriack','ifood','Z4',43,true),
  ('Salada BMT','ifood','E',37.5,true),
  ('Salada BMT','ifood','F',38,true),
  ('Salada BMT','ifood','G',39,true),
  ('Salada BMT','ifood','H',39.5,true),
  ('Salada BMT','ifood','Z1',41,true),
  ('Salada BMT','ifood','Z2',42,true),
  ('Salada BMT','ifood','Z3',43,true),
  ('Salada BMT','ifood','Z4',44,true),
  ('Salada Supreme','ifood','E',38.5,true),
  ('Salada Supreme','ifood','F',39,true),
  ('Salada Supreme','ifood','G',40,true),
  ('Salada Supreme','ifood','H',40.5,true),
  ('Salada Supreme','ifood','Z1',42,true),
  ('Salada Supreme','ifood','Z2',43,true),
  ('Salada Supreme','ifood','Z3',44,true),
  ('Salada Supreme','ifood','Z4',45,true),
  ('Salada Carne Seca','ifood','E',38.5,true),
  ('Salada Carne Seca','ifood','F',39,true),
  ('Salada Carne Seca','ifood','G',40,true),
  ('Salada Carne Seca','ifood','H',40.5,true),
  ('Salada Carne Seca','ifood','Z1',42,true),
  ('Salada Carne Seca','ifood','Z2',43,true),
  ('Salada Carne Seca','ifood','Z3',44,true),
  ('Salada Carne Seca','ifood','Z4',45,true)
) as v(nome, canal, tabela, preco, desatualizado)
join produtos p on p.organizacao_id='00000000-0000-0000-0000-000000000001' and p.nome=v.nome
on conflict (produto_id, canal, tabela) do update set preco=excluded.preco, desatualizado=excluded.desatualizado;
commit;
