-- MIGRATION 010 — Preços de BALCÃO dos "dobro de recheio" em todas as tabelas
-- Fonte: (TAB. PREÇO) Balcão Subway - Out.25 (Ajustado 13.10).
-- Corrige a migration 005 (que usara valores da planilha de CMV, errados p/ balcão)
-- e preenche B–F/AERO. Dobro de sabor/carne = 8/8/8,5/8,5/9/9/10/12; dobro de queijo
-- (mussarela) = 5/5/5,5/5,5/6/6/7/7. Idempotente. Rode no Supabase.
begin;
insert into produto_precos (produto_id, canal, tabela, preco, desatualizado)
select p.id, 'balcao'::canal, v.tabela, v.preco, false
from (values
  ('S2C-DR-EMP','A',8),
  ('S2C-DR-EMP','B',8),
  ('S2C-DR-EMP','C',8.5),
  ('S2C-DR-EMP','D',8.5),
  ('S2C-DR-EMP','E',9),
  ('S2C-DR-EMP','F',9),
  ('S2C-DR-EMP','AERO A',10),
  ('S2C-DR-EMP','AERO B',12),
  ('S2C-DR-FRA','A',8),
  ('S2C-DR-FRA','B',8),
  ('S2C-DR-FRA','C',8.5),
  ('S2C-DR-FRA','D',8.5),
  ('S2C-DR-FRA','E',9),
  ('S2C-DR-FRA','F',9),
  ('S2C-DR-FRA','AERO A',10),
  ('S2C-DR-FRA','AERO B',12),
  ('S2C-DR-CHU','A',8),
  ('S2C-DR-CHU','B',8),
  ('S2C-DR-CHU','C',8.5),
  ('S2C-DR-CHU','D',8.5),
  ('S2C-DR-CHU','E',9),
  ('S2C-DR-CHU','F',9),
  ('S2C-DR-CHU','AERO A',10),
  ('S2C-DR-CHU','AERO B',12),
  ('S2C-DR-CSE','A',8),
  ('S2C-DR-CSE','B',8),
  ('S2C-DR-CSE','C',8.5),
  ('S2C-DR-CSE','D',8.5),
  ('S2C-DR-CSE','E',9),
  ('S2C-DR-CSE','F',9),
  ('S2C-DR-CSE','AERO A',10),
  ('S2C-DR-CSE','AERO B',12),
  ('S2C-DR-BMT','A',8),
  ('S2C-DR-BMT','B',8),
  ('S2C-DR-BMT','C',8.5),
  ('S2C-DR-BMT','D',8.5),
  ('S2C-DR-BMT','E',9),
  ('S2C-DR-BMT','F',9),
  ('S2C-DR-BMT','AERO A',10),
  ('S2C-DR-BMT','AERO B',12),
  ('S2C-DR-STK','A',8),
  ('S2C-DR-STK','B',8),
  ('S2C-DR-STK','C',8.5),
  ('S2C-DR-STK','D',8.5),
  ('S2C-DR-STK','E',9),
  ('S2C-DR-STK','F',9),
  ('S2C-DR-STK','AERO A',10),
  ('S2C-DR-STK','AERO B',12),
  ('S2C-DR-DEF','A',8),
  ('S2C-DR-DEF','B',8),
  ('S2C-DR-DEF','C',8.5),
  ('S2C-DR-DEF','D',8.5),
  ('S2C-DR-DEF','E',9),
  ('S2C-DR-DEF','F',9),
  ('S2C-DR-DEF','AERO A',10),
  ('S2C-DR-DEF','AERO B',12),
  ('S2C-DR-TER','A',8),
  ('S2C-DR-TER','B',8),
  ('S2C-DR-TER','C',8.5),
  ('S2C-DR-TER','D',8.5),
  ('S2C-DR-TER','E',9),
  ('S2C-DR-TER','F',9),
  ('S2C-DR-TER','AERO A',10),
  ('S2C-DR-TER','AERO B',12),
  ('S2C-DR-SUP','A',8),
  ('S2C-DR-SUP','B',8),
  ('S2C-DR-SUP','C',8.5),
  ('S2C-DR-SUP','D',8.5),
  ('S2C-DR-SUP','E',9),
  ('S2C-DR-SUP','F',9),
  ('S2C-DR-SUP','AERO A',10),
  ('S2C-DR-SUP','AERO B',12),
  ('S2C-DR-MUS','A',5),
  ('S2C-DR-MUS','B',5),
  ('S2C-DR-MUS','C',5.5),
  ('S2C-DR-MUS','D',5.5),
  ('S2C-DR-MUS','E',6),
  ('S2C-DR-MUS','F',6),
  ('S2C-DR-MUS','AERO A',7),
  ('S2C-DR-MUS','AERO B',7)
) as v(sku, tabela, preco)
join produtos p on p.organizacao_id='00000000-0000-0000-0000-000000000001' and p.sku=v.sku
on conflict (produto_id, canal, tabela) do update set preco=excluded.preco, desatualizado=false;
commit;
